---
title: "visit_scotland_cleaning"
output: html_notebook
---
# Librarys
```{r}
library(tidyverse)
library(janitor)

```

# Read in the data and run clean names
```{r}
regional_dom_tour <- read_csv("data/regional_domestic_tourism.csv") %>%  clean_names()
scot_accom_occ <- read_csv("data/scottish_accomodation_occupancy.csv") %>%  clean_names()
day_visits_activ <- read_csv("data/tourism_day_visits_activities.csv") %>%  clean_names()
day_visits_demo <- read_csv("data/tourism_day_visits_demographics.csv") %>%  clean_names()
day_visits_loca <- read_csv("data/tourism_day_visits_location.csv") %>%  clean_names()
day_visits_trans <- read_csv("data/tourism_day_visits_transport.csv") %>%  clean_names()
```
Explore the data
```{r}
regional_dom_tour %>%
  head()
```

```{r}
scot_accom_occ %>% 
  head()
```

```{r}
day_visits_activ %>% 
  head()
```

```{r}
day_visits_demo %>% 
  head()
```

```{r}
day_visits_loca %>% 
  head()
```

```{r}
day_visits_trans %>% 
  head()
```
# clean the indiviudal data sets

```{r}

```
# left join the table together by feature_code
```{r}
day_visits_activity_demographic <- left_join(day_visits_activ, day_visits_demo, by = "feature_code")

day_visits_activity_demographic
```
# left join the table together by feature_code

```{r}
day_visits_location_transport <- left_join(day_visits_loca, day_visits_trans, by = "feature_code")

day_visits_location_transport
```
# try not to explode laptop with a join
```{r}
# left_join(day_visits_activity_demographic, day_visits_location_transport, by = "feature_code")
```

when you open this back up, clean the data sets of variables before trying joining again